name: Mostrar Variables de Entorno

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  show-env-vars:
    runs-on: ubuntu-latest
    
    steps:
      # Paso 1: Checkout del código
      - name: Checkout code
        uses: actions/checkout@v2
        
      # Paso 2: Mostrar todas las variables de entorno
      - name: Mostrar variables de entorno
        run: |
          echo "Variables de entorno disponibles:"
          printenv
          
      # Paso 3: Mostrar variables específicas (si se desea)
      - name: Mostrar una variable específica
        run: echo "La variable HOME es: $HOME"
